"use strict";
exports.__esModule = true;
var express_1 = require("express");
var usuarios_1 = require("../controllers/usuarios");
var router = express_1.Router();
router.get("/", usuarios_1.getUsuarios);
router.get("/:id", usuarios_1.getUsuario);
router.post("/", usuarios_1.postUsuario);
router.put("/:id", usuarios_1.putUsuario);
router["delete"]("/:id", usuarios_1.deleteUsuario);
exports["default"] = router;
